name: "Build Server"
description: "Build Server"

inputs:
    target:
        required: true

runs:
    using: "composite"
    steps:
      - name: Bundle Server
        shell: bash
        working-directory: ./homebrewdj
        #run: deno task compile:${{ inputs.target }}:release
        run: |
          deno bundle --minify main.ts > ../dist/bundled.js
          cp config.json ../dist/config.json