name: "Bundle Server"
description: "Bundle Server"

inputs:
    target:
        required: true

runs:
    using: "composite"
    steps:
      - name: Bundle Server
        shell: bash
        working-directory: ./homebrewdj
        #run: deno task compile:${{ inputs.target }}:release
        run: |
          deno bundle --minify bin/traktor_setup.ts > ../dist/homebrewdj_traktor.js
          deno bundle --minify bin/webui_only.ts > ../dist/homebrewdj_controller.js
          cp config.json ../dist/config.json