name: "Build Server"
description: "Build Server"

inputs:
    target:
        required: true

runs:
    using: "composite"
    steps:
      - name: Build Server
        shell: bash
        working-directory: ./server
        run: deno task compile:${{ inputs.target }}:release