name: "Build Web Frontend"
description: "Build Web Frontend"

inputs:
    target:
        required: true

runs:
    using: "composite"
    steps:
        - name: Build Web UI
          shell: bash
          working-directory: ./web
          run: yarn && yarn build:release