name: "Build Web Frontend"
description: "Build Web Frontend"

inputs:
    target:
        required: true

runs:
    using: "composite"
    steps:
        - name: Build Widgets
          shell: bash
          working-directory: ./widgets
          run: yarn build
          
        - name: Build Web UI
          shell: bash
          working-directory: ./react-app
          run: yarn build