name: "Build MIDI Driver"
description: "Build MIDI Driver"

inputs:
    target:
        required: true

runs:
    using: "composite"
    steps:
      - name: Build MIDI Driver (Mac)
        shell: bash
        working-directory: ./midi-driver
        #run: cargo build -p midi-driver --release
        run: deno task compile:${{ inputs.target }}:release