name: "Compile Executable"
description: "Compile Executable"

inputs:
  target:
    required: true

runs:
  using: "composite"
  steps:
    - name: Compile Deno Executable
      shell: bash
      working-directory: ./dist
      run: |
        if [ "${{ inputs.target }}" = "linux" ]; then
          deno compile \
            --include libmidi_driver.so \
            --include react-app \
            --output homebrewdj \
            main.ts

        elif [ "${{ inputs.target }}" = "mac" ]; then
          deno compile \
            --include libmidi_driver.dylib \
            --include react-app \
            --output homebrewdj \
            main.ts

        elif [ "${{ inputs.target }}" = "win" ]; then
          deno compile \
            --include midi_driver.dll \
            --include react-app \
            --output homebrewdj.exe \
            main.ts
        fi
