name: "Build Bindings"
description: "Build Bindings"

#inputs:
#    target:
#        required: true

runs:
    using: "composite"
    steps:
        - name: Export Bindings
          shell: bash
          working-directory: ./definitions
          run: cargo test export_bindings