#name: Release on vx.x.x Tag
name: "Build multiplatform"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: mac
          - os: windows-latest
            target: win

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/build-webui
        with:
          target: ${{ matrix.target }}
      - uses: ./.github/actions/build-driver
        with:
          target: ${{ matrix.target }}
      - uses: ./.github/actions/build-server
        with:
          target: ${{ matrix.target }}

#      - uses: ./.github/actions/compile-executable
#        with:
#          target: ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: |
            dist/*
#          midi-driver/bindings/*
#          midi-driver/native/*
#
#          react-app/dist/*
#          midi-driver/target/release/libmidi_driver.dylib
#          midi-driver/target/release/libmidi_driver.so
#          midi-driver/target/release/midi_driver.dll
#          homebrewdj/dist/bundled.js

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: LICENSE
          path: |
            LICENSE

  compile-executable:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: mac
          - os: windows-latest
            target: win
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Inspect dist
        run: ls -R dist

      - name: Compile Deno Executable
        shell: bash
        working-directory: dist
        run: |
          if [ "${{ matrix.target }}" = "linux" ]; then
            deno compile \
              --include libmidi_driver.so \
              --include react-app \
              --output homebrewdj \
              bundled.js

          elif [ "${{ matrix.target }}" = "mac" ]; then
            deno compile \
              --include libmidi_driver.dylib \
              --include react-app \
              --output homebrewdj \
              bundled.js

          elif [ "${{ matrix.target }}" = "win" ]; then
            deno compile \
              --include midi_driver.dll \
              --include react-app \
              --output homebrewdj.exe \
              bundled.js
          fi
              
  create-release:
      runs-on: ubuntu-latest
      needs: compile-executable
      steps:
        - name: Download all build artifacts
          uses: actions/download-artifact@v4

        - name: Inspect dist
          run: ls -R dist
          
        - name: Release (on tags only)
          uses: softprops/action-gh-release@master
          if: startsWith(github.ref, 'refs/tags/')
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            draft: true
            files: |
              dist/build-linux/**/homebrewdj.linux
              dist/build-mac/**/homebrewdj.mac
              dist/build-win/**/homebrewdj.exe
              dist/build-mac/**/libmidi_driver.dylib
              dist/build-linux/**/libmidi_driver.so
              dist/build-win/**/midi_driver.dll
              dist/**/LICENSE