#name: Release on vx.x.x Tag
name: "Build multiplatform"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  driver:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: mac
          - os: windows-latest
            target: win
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libjack-dev libasound-dev
      - uses: ./.github/actions/build-driver
        with:
          target: ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: "native-${{ matrix.target }}"
          path: |
            ./native/*
            ./midi-driver/target/release/*.dll
            ./midi-driver/target/release/*.dylib
            ./midi-driver/target/release/*.so

  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/build-webui
      - uses: ./.github/actions/build-server
      - uses: actions/upload-artifact@v4
        with:
          name: js
          path: |
            dist/homebrewdj_traktor.js
            dist/homebrewdj_controller.js
            dist/config.json
      - uses: actions/upload-artifact@v4
        with:
          name: webui
          path: |
            dist/react-app/*

      - uses: actions/upload-artifact@v4
        with:
          name: LICENSE
          path: |
            LICENSE

  compile-executable:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: mac
          - os: windows-latest
            target: win
    runs-on: ${{ matrix.os }}
    needs: 
      - build
      - driver
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.7.7

      - name: Prepare Build Folder
        shell: bash
        run: |
          mkdir build
          cp -r LICENSE/LICENSE build/LICENSE
          cp -r webui build/webui
          cp js/homebrewdj_traktor.js build/homebrewdj_traktor.js
          cp js/homebrewdj_controller.js build/homebrewdj_controller.js
          cp js/config.json build/config.json
          cp native-linux/midi-driver/target/release/libmidi_driver.so build/libmidi_driver.so 2>/dev/null || true
          cp native-mac/midi-driver/target/release/libmidi_driver.dylib build/libmidi_driver.dylib 2>/dev/null || true
          cp native-win/midi-driver/target/release/midi_driver.dll build/midi_driver.dll 2>/dev/null || true

      - name: Inspect workspace
        run: ls -R .

      - name: Compile Deno Executable
        shell: bash
        working-directory: build
        run: |
          if [ "${{ matrix.target }}" = "linux" ]; then
            deno compile -A \
              --include libmidi_driver.so \
              --include webui \
              --output homebrewdj \
              homebrewdj_traktor.js

          elif [ "${{ matrix.target }}" = "mac" ]; then
            deno compile -A \
              --include libmidi_driver.dylib \
              --include webui \
              --output homebrewdj \
              homebrewdj_traktor.js

          elif [ "${{ matrix.target }}" = "win" ]; then
            deno compile -A \
              --include midi_driver.dll \
              --include webui \
              --output homebrewdj.exe \
              homebrewdj_traktor.js
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: homebrewdj-${{ matrix.target }}
          path: |
            build/homebrewdj.exe
            build/homebrewdj
            build/config.json
            build/LICENSE
              
  create-release:
      runs-on: ubuntu-latest
      needs:
        - compile-executable
      steps:
        - name: Download all build artifacts
          uses: actions/download-artifact@v4

        - name: Inspect dist
          run: ls -R .

        - name: Package releases
          run: |
            chmod +x homebrewdj-linux/homebrewdj
            chmod +x homebrewdj-mac/homebrewdj
            zip -r homebrewdj-linux.zip homebrewdj-linux
            zip -r homebrewdj-win.zip homebrewdj-win
            zip -r homebrewdj-mac.zip homebrewdj-mac
            zip -r webui.zip webui
          
        - name: Release (on tags only)
          uses: softprops/action-gh-release@master
          if: startsWith(github.ref, 'refs/tags/')
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            draft: true
            files: |
              homebrewdj-linux.zip
              homebrewdj-win.zip
              homebrewdj-mac.zip
              webui.zip
              js/homebrewdj*.js
              js/config.json
              native-win/midi-driver/target/release/*.dll
              native-mac/midi-driver/target/release/*.dylib
              native-linux/midi-driver/target/release/*.so